name: Deploy static content to Test Pages

on:
  push:
    branches: ['test']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages-test'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages-test
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Set environment variable for test
        run: echo "VITE_ENV=test" >> $GITHUB_ENV
      - name: Build
        run: npm run build
      - name: Create test directory and move contents
        run: |
          mkdir -p dist/test
          mv dist/* dist/test/
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist/test'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          folder: 'dist/test'
